on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libfuse-dev
      - uses: actions/checkout@v4
      - name: Build
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}